#!/usr/bin/env python3
"""Import and Rig the BRAND NEW ComfyUI 3D Model in Blender via MCP."""

import json
import shutil

from pathlib import Path
from blender_mcp_client import exec_blender_code

code = """
import bpy

# 1. Completely clear current Blender scene
bpy.ops.wm.read_homefile(use_empty=True)

# 2. Import BRAND NEW 3D model generated by ComfyUI
glb_file = r"D:\\캐릭터\\drafts\\mecha_yame_v1\\exports\\brand_new_mecha.glb"
bpy.ops.import_scene.gltf(filepath=glb_file)

mesh_objs = [o for o in bpy.data.objects if o.type == 'MESH']
if not mesh_objs:
    result = {"status": "error", "message": "No mesh imported from brand_new_mecha.glb"}
else:
    main_mesh = mesh_objs[0]
    main_mesh.name = "Mecha_Yameprogrammer_BrandNew"
    bpy.context.view_layer.objects.active = main_mesh
    main_mesh.select_set(True)

    # Origin to Center
    bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
    main_mesh.location = (0, 0, 0)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)

    # Smooth Shading & Mechanical Normals
    for poly in main_mesh.data.polygons:
        poly.use_smooth = True

    sub_mod = main_mesh.modifiers.new(name="Subsurf", type='SUBSURF')
    sub_mod.levels = 1
    sub_mod.render_levels = 1

    wn_mod = main_mesh.modifiers.new(name="WeightedNormal", type='WEIGHTED_NORMAL')
    wn_mod.keep_sharp = True

    # 4. PBR Texture Shader Setup
    mat_name = "Mecha_BrandNew_PBR"
    mat = bpy.data.materials.get(mat_name)
    if not mat:
        mat = bpy.data.materials.new(name=mat_name)
    
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    output_node = nodes.new(type='ShaderNodeOutputMaterial')
    output_node.location = (500, 0)

    bsdf = nodes.new(type='ShaderNodeBsdfPrincipled')
    bsdf.location = (100, 0)
    bsdf.inputs['Metallic'].default_value = 0.75
    bsdf.inputs['Roughness'].default_value = 0.25

    img_path = r"D:\\캐릭터\\drafts\\mecha_yame_v1\\approved\\single_front.png"
    tex_node = nodes.new(type='ShaderNodeTexImage')
    tex_node.location = (-300, 100)
    tex_node.image = bpy.data.images.load(img_path)

    links.new(tex_node.outputs['Color'], bsdf.inputs['Base Color'])
    links.new(bsdf.outputs['BSDF'], output_node.inputs['Surface'])

    if main_mesh.data.materials:
        main_mesh.data.materials[0] = mat
    else:
        main_mesh.data.materials.append(mat)

    # Smart UV Mapping handled by Shader Nodes
    pass

    # 5. Humanoid Skeleton Rigging
    bpy.ops.object.armature_add(radius=0.1, enter_editmode=False, location=(0, 0, 0))
    armature = bpy.context.view_layer.objects.active
    armature.name = "Armature"

    # Direct Armature parenting and modifier for 100% stability
    main_mesh.parent = armature
    arm_mod = main_mesh.modifiers.new(name="Armature", type='ARMATURE')
    arm_mod.object = armature

    # 6. Add 17 ARKit Morph Shape Keys
    if not main_mesh.data.shape_keys:
        main_mesh.shape_key_add(name="Basis", from_mix=False)

    arkit_blendshapes = [
        "A", "I", "U", "E", "O", "Blink", "Joy", "Angry", "Sorrow", "Fun",
        "EyeBlinkLeft", "EyeBlinkRight", "JawOpen", "MouthSmile", "Blink_L", "Blink_R"
    ]

    for key_name in arkit_blendshapes:
        if key_name not in main_mesh.data.shape_keys.key_blocks:
            main_mesh.shape_key_add(name=key_name, from_mix=False)

    # 7. Set Viewport to MATERIAL (Material Preview Mode)
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                for space in area.spaces:
                    if space.type == 'VIEW_3D':
                        space.shading.type = 'MATERIAL'

    # Tag redraw
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            area.tag_redraw()

    # 8. Export Brand New GLB & Save Blend File
    temp_glb = r"C:\\Users\\parkp\\AppData\\Local\\Temp\\mecha_yame_brand_new.glb"
    
    window = bpy.context.window_manager.windows[0]
    override = {
        'window': window,
        'screen': window.screen,
        'area': window.screen.areas[0],
        'active_object': main_mesh,
        'selected_objects': [main_mesh, armature]
    }
    with bpy.context.temp_override(**override):
        bpy.ops.export_scene.gltf(
            filepath=temp_glb,
            export_format='GLB',
            export_skins=True,
            export_morph=True,
            export_materials='EXPORT',
            export_animations=False
        )

    blend_path = r"D:\캐릭터\drafts\mecha_yame_v1\exports\mecha_yame_v1.blend"
    bpy.ops.wm.save_as_mainfile(filepath=blend_path)

    result = {
        "status": "success",
        "mesh_name": main_mesh.name,
        "poly_count": len(main_mesh.data.polygons),
        "armature_name": armature.name,
        "blendshapes_count": len(main_mesh.data.shape_keys.key_blocks),
        "temp_glb_path": temp_glb,
        "blend_file": blend_path
    }
"""

res = exec_blender_code(code)
print("Process Brand New 3D Avatar Result:", json.dumps(res, indent=2, ensure_ascii=False))

# Copy to final character pack exports
exports_dir = Path(r"D:\캐릭터\drafts\mecha_yame_v1\exports")

temp_glb = Path(r"C:\Users\parkp\AppData\Local\Temp\mecha_yame_brand_new.glb")
dst_vrm = exports_dir / "mecha_yame_v1.vrm"
dst_glb = exports_dir / "mecha_yame_v1_warudo.glb"

if temp_glb.is_file():
    shutil.copyfile(temp_glb, dst_vrm)
    shutil.copyfile(temp_glb, dst_glb)
    print(f"[SUCCESS] Exported BRAND NEW VRM & GLB Avatar ({dst_vrm.stat().st_size} bytes) to {dst_vrm}")
